In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

In [2]:
data = {
    "Age": [25, 30, 35, 40, 45, 50, 55, 60],
    "BMI": [22, 25, 27, 30, 32, 35, 37, 40],
    "Exercise Hours": [5, 4, 3, 2, 2, 1, 1, 0],
    "Medical Expense (₹ Thousands)": [90, 120, 160, 220, 280, 340, 410, 500]
}
df = pd.DataFrame(data)
print(df)

   Age  BMI  Exercise Hours  Medical Expense (₹ Thousands)
0   25   22               5                             90
1   30   25               4                            120
2   35   27               3                            160
3   40   30               2                            220
4   45   32               2                            280
5   50   35               1                            340
6   55   37               1                            410
7   60   40               0                            500


In [3]:
X = df[["Age", "BMI", "Exercise Hours"]]
y = df["Medical Expense (₹ Thousands)"]
print(X)

   Age  BMI  Exercise Hours
0   25   22               5
1   30   25               4
2   35   27               3
3   40   30               2
4   45   32               2
5   50   35               1
6   55   37               1
7   60   40               0


In [4]:
print(y)

0     90
1    120
2    160
3    220
4    280
5    340
6    410
7    500
Name: Medical Expense (₹ Thousands), dtype: int64


In [5]:
linear_model = LinearRegression()
linear_model.fit(X, y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [6]:
poly_pipeline = Pipeline([
    ("poly", PolynomialFeatures(degree=4)),
    ("linear", LinearRegression())
])

poly_pipeline.fit(X, y)

,steps,"[('poly', ...), ('linear', ...)]"
,transform_input,None
,memory,None
,verbose,False
,degree,4
,interaction_only,False
,include_bias,True
,order,'C'
,fit_intercept,True
,copy_X,True
,tol,1e-06


In [7]:
new_patient = [[42, 31, 2]]

linear_prediction = linear_model.predict(new_patient)
poly_prediction = poly_pipeline.predict(new_patient)

print("Linear Regression Prediction:")
print(linear_prediction)

print("\nPolynomial Regression Prediction:")
print(poly_prediction)


Linear Regression Prediction:
[252.66666667]

Polynomial Regression Prediction:
[234.13946438]


C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


In [8]:
lasso = Lasso(alpha=0.2)
lasso.fit(X, y)

C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.255e+02, tolerance: 1.468e+01
  model = cd_fast.enet_coordinate_descent(


,alpha,0.2
,fit_intercept,True
,precompute,False
,copy_X,True
,max_iter,1000
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [9]:
ridge = Ridge(alpha=2.0)
ridge.fit(X, y)

,alpha,2.0
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [10]:
elastic = ElasticNet(alpha=0.2, l1_ratio=0.6)
elastic.fit(X, y)

,alpha,0.2
,l1_ratio,0.6
,fit_intercept,True
,precompute,False
,max_iter,1000
,copy_X,True
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [11]:
# -------------------------
print("\nLasso Coefficients:")
print(lasso.coef_)

print("\nRidge Coefficients:")
print(ridge.coef_)

print("\nElasticNet Coefficients:")
print(elastic.coef_)


Lasso Coefficients:
[ 4.60873763 26.02595825 45.20340022]

Ridge Coefficients:
[10.0193666   6.05604921 10.35771246]

ElasticNet Coefficients:
[ 9.74098076  9.52868341 21.31647612]


In [12]:
scores = cross_val_score(elastic, X, y, cv=4)

print("\nCross Validation Scores:")
print(scores)

print("\nAverage Cross Validation Score:")
print(scores.mean())


Cross Validation Scores:
[-1.29209563e+01  7.49088767e-01  7.03169004e-01  1.65136089e-03]

Average Cross Validation Score:
-2.8667618010633924
