In [1]:
import numpy as np
person=np.array([170,65,20])
print(person)

[170  65  20]


In [5]:
print('Height:', person[0],'Weight:', person[1], 'Age:', person[2])

Height: 170 Weight: 65 Age: 20


In [6]:
v1=3*person
print(v1)

[510 195  60]


In [7]:
v2=2*person
print(v2)

[340 130  40]


In [8]:
mag=np.linalg.norm(person)
print(mag)

183.09833423600554


In [9]:
features=len(person)
print(features)

3


In [10]:
person2=np.array([160,55,18])
add=person+person2
print(add)

[330 120  38]
