In [1]:
import numpy as np
sales_data = np.array([   [120, 150, 180],   [100, 130, 170],   [140, 160, 190]])
shape=sales_data.shape
print('The shape of the matrix is: ',shape)

The shape of the matrix is:  (3, 3)


In [4]:
bonus_sales = np.array([ [10, 15, 20], [5, 10, 15],  [12, 14, 18]])
result=sales_data+bonus_sales
print('The result of sales and bonus is:\n', result)

The result of sales and bonus is:
 [[130 165 200]
 [105 140 185]
 [152 174 208]]


In [5]:
mul=3*sales_data
print(mul)

[[360 450 540]
 [300 390 510]
 [420 480 570]]


In [6]:
transpose=sales_data.T
print('The transpose of the sales_data is:\n',transpose )

The transpose of the sales_data is:
 [[120 100 140]
 [150 130 160]
 [180 170 190]]


In [7]:
A = np.array([ [4, 2, 1], [3, 5, 2],[1, 2, 3]])
determinant=np.linalg.det(A)
print('The deteminant of the matrix A is: ',determinant)

The deteminant of the matrix A is:  31.0


In [8]:
if determinant==0:
    print('Singular')
else:
    print('Non Singular')

Non Singular


In [9]:
inverse=np.linalg.inv(A)
print(inverse)

[[ 0.35483871 -0.12903226 -0.03225806]
 [-0.22580645  0.35483871 -0.16129032]
 [ 0.03225806 -0.19354839  0.4516129 ]]


In [10]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
rank=np.linalg.matrix_rank(A)
print('The rank of matrix A is:', rank)

The rank of matrix A is: 3
