In [2]:
import numpy as np
student_scores = np.array([  [75, 82, 88],  [68, 79, 91],   [80, 85, 95]])
shape=student_scores.shape
print('The shape of the student_scores is: ',shape)

The shape of the student_scores is:  (3, 3)


In [3]:
improvement_scores = np.array([ [5, 4, 3],[6, 5, 4],  [4, 3, 2]])
result=student_scores+improvement_scores
print('The result of 2 data are:\n',result)

The result of 2 data are:
 [[80 86 91]
 [74 84 95]
 [84 88 97]]


In [4]:
mul=2*student_scores
print(mul)

[[150 164 176]
 [136 158 182]
 [160 170 190]]


In [5]:
transpose=student_scores.T
print('The transpose of studnet scores is:\n',transpose)

The transpose of studnet scores is:
 [[75 68 80]
 [82 79 85]
 [88 91 95]]


In [6]:
B = np.array([[2, 1, 3],[1, 4, 2], [3, 2, 5]])
det=np.linalg.det(B)
print('The determinant of B is:',det)

The determinant of B is: 2.999999999999999


In [7]:
if det==0:
    print('Singular')
else:
    print('Non-Singular')

Non-Singular


In [8]:
inverse=np.linalg.inv(B)
print('The inverse of matrix B is:\n',inverse)

The inverse of matrix B is:
 [[ 5.33333333  0.33333333 -3.33333333]
 [ 0.33333333  0.33333333 -0.33333333]
 [-3.33333333 -0.33333333  2.33333333]]


In [9]:
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
rank=np.linalg.matrix_rank(B)
print('The rank of matrix B is: ',rank)

The rank of matrix B is:  3
