In [143]:
# Question 1
# To find the square of a number from user input
def square(x):
    return x**2
x=int(input('Enter the value of x:'))
result=square(x)
print('The Square of',x,'is:',result)

Enter the value of x: 2


The Square of 2 is: 4


In [12]:
# To find the cube of a number from user input
def cube(x):
    return x**3
x=int(input('Enter the value of x: '))
result=cube(x)
print('The cube of',x,'is: ',result)

Enter the value of x:  2


The cube of 2 is:  8


In [14]:
# To find the average of 3 numbers from user input
def average(a,b,c):
    return (a+b+c)/3
a=int(input('Enter the value of a: '))
b=int(input('Enter the value of b: '))
c=int(input('Enter the value of c: '))
result=average(a,b,c)
print('The average of 3 numbers is: ',result)

Enter the value of a:  1
Enter the value of b:  2
Enter the value of c:  3


The average of 3 numbers is:  2.0


In [15]:
# Question 2
# Area of a circle
r=int(input('Enter the radius of the circle'))
pi=3.14
area=pi*r*r
print('The area of the circle is: ',area)

Enter the radius of the circle 4


The area of the circle is:  50.24


In [30]:
# Question 3 and Question 4 combined
import pandas as pd
df1=pd.read_excel('equation_data.xlsx')
print(data)
for index,row in df1.iterrows():
    a=row['a']
    b=row['b']
    c=row['c']
    x=(c-b)/a
    #Slope and Intercept
    slope=a
    intercept=b
    print(f"Equation {row['Equation_ID']}: {a}x + {b} = {c}")
    print(f"x = {x}\n")
    print(f"Slope = {slope}")
    print(f"Y-intercept = {intercept}\n")

   Equation_ID  a   b   c
0            1  2   4  10
1            2  3   6  18
2            3  5  10  35
3            4  4   8  24
4            5  6  12  42
5            6  7  14  56
6            7  8  16  72
7            8  9  18  90
Equation 1: 2x + 4 = 10
x = 3.0

Slope = 2
Y-intercept = 4

Equation 2: 3x + 6 = 18
x = 4.0

Slope = 3
Y-intercept = 6

Equation 3: 5x + 10 = 35
x = 5.0

Slope = 5
Y-intercept = 10

Equation 4: 4x + 8 = 24
x = 4.0

Slope = 4
Y-intercept = 8

Equation 5: 6x + 12 = 42
x = 5.0

Slope = 6
Y-intercept = 12

Equation 6: 7x + 14 = 56
x = 6.0

Slope = 7
Y-intercept = 14

Equation 7: 8x + 16 = 72
x = 7.0

Slope = 8
Y-intercept = 16

Equation 8: 9x + 18 = 90
x = 8.0

Slope = 9
Y-intercept = 18



In [41]:
# Question 5
import statistics as st
df2=pd.read_excel('student_marks.xlsx')
print(df2)
# Mean
mean=st.mean(df2['Marks'])
print('Mean = ',mean)
#median
median=st.median(df2['Marks'])
print('Median =',median)
#mode
mode=st.mode(df2['Marks'])
print('Mode =',mode)

    Student_ID  Marks
0            1     55
1            2     62
2            3     70
3            4     80
4            5     90
5            6     65
6            7     75
7            8     85
8            9     70
9           10     95
10          11     60
11          12     75
12          13     80
13          14     85
14          15    100
Mean =  76.46666666666667
Median = 75
Mode = 70


In [46]:
# Question 6
df2.loc[len(df2)]=500
mean=st.mean(df2['Marks'])
print('Mean =',mean)
median=st.median(df2['Marks'])
print('Median =',median)

Mean = 147.05555555555554
Median = 80.0


In [50]:
# Question 7
df3=pd.read_excel('sales_data.xlsx')
print(df3)
variance=st.variance(df3['Sales'])
print('\n')
print('Variance =',variance)
std=st.stdev(df3['Sales'])
print('std =',std)

        Month  Sales
0     January  12000
1    February  15000
2       March  17000
3       April  16000
4         May  18000
5        June  20000
6        July  22000
7      August  21000
8   September  19000
9     October  23000
10   November  24000
11   December  26000


Variance = 16446969.696969697
std = 4055.4863699647294


In [58]:
# Question 8
df4=pd.read_excel('probability_data.xlsx')
print(df4)
experiment = df4["Experiment"][0]
print("Experiment =", experiment)
outcomes = df4["Outcome"].unique()
print("Outcomes =", outcomes)
heads = (df4["Outcome"] == "Head").sum()
tails = (df4["Outcome"] == "Tail").sum()
total = len(df4)
probability1 = heads / total
probability2 = tails / total
print("Number of Heads =", heads)
print("Number of Tails =", tails)
print("Total Outcomes =", total)
print("Probability of Head =", probability1)
print("Probability of Tail =", probability2)

  Experiment Outcome
0  Coin Toss    Head
1  Coin Toss    Tail
2  Coin Toss    Head
3  Coin Toss    Head
4  Coin Toss    Tail
5  Coin Toss    Head
6  Coin Toss    Tail
7  Coin Toss    Tail
8  Coin Toss    Head
9  Coin Toss    Head
Experiment = Coin Toss
Outcomes = ['Head' 'Tail']
Number of Heads = 6
Number of Tails = 4
Total Outcomes = 10
Probability of Head = 0.6
Probability of Tail = 0.4


In [78]:
# Question 9
import random
outcome=[]
for i in range(10):
    toss=random.choice(['Head','Tail'])
    outcome.append(toss)
print(outcome)
heads=outcome.count('Head')
tails=outcome.count('Tail')
total=len(outcome)
print("Probability of Head =", heads / total)
print("Probability of Tail =", tails / total)

['Head', 'Tail', 'Head', 'Head', 'Head', 'Head', 'Tail', 'Tail', 'Head', 'Tail']
Probability of Head = 0.6
Probability of Tail = 0.4


In [131]:
# Question 10
import numpy as np
df5=pd.read_excel('vector_data.xlsx')
print(df5)
for index,rows in df5.iterrows():
    x=rows['X']
    y=rows['Y']
    vector=np.array([x,y])
    scalar_vector=2*vector
    magnitude=np.linalg.norm(vector)
    print("\n", rows['Vector'])
    print("Original Vector:", vector)
    print("Scalar Multiplication :", scalar_vector)
    print("Magnitude:", magnitude)

  Vector  X  Y
0     V1  1  3
1     V2  2  5
2     V3  3  1
3     V4  4  7
4     V5  5  4

 V1
Original Vector: [1 3]
Scalar Multiplication : [2 6]
Magnitude: 3.1622776601683795

 V2
Original Vector: [2 5]
Scalar Multiplication : [ 4 10]
Magnitude: 5.385164807134504

 V3
Original Vector: [3 1]
Scalar Multiplication : [6 2]
Magnitude: 3.1622776601683795

 V4
Original Vector: [4 7]
Scalar Multiplication : [ 8 14]
Magnitude: 8.06225774829855

 V5
Original Vector: [5 4]
Scalar Multiplication : [10  8]
Magnitude: 6.4031242374328485


In [91]:
v1=np.array([df5.loc[0,'X'],df5.loc[0,'Y']])
v2=np.array([df5.loc[1,'X'],df5.loc[1,'Y']])
add=v1+v2
print('Addition of two vectors is: ',add)

Addition of two vectors is:  [3 8]


In [92]:
# Question 11
df6=pd.read_excel('matrix_data.xlsx')
print(df6)

  Matrix_ID  m11  m12  m21  m22
0        M1    2    3    1    4
1        M2    1    2    3    5
2        M3    4    1    2    6
3        M4    3    5    2    7
4        M5    5    2    4    8


In [106]:
for index,rows in df6.iterrows():
    M11=rows['m11']
    M12=rows['m12']
    M21=rows['m21']
    M22=rows['m22']
    matrix=np.array([[M11,M12],[M21,M22]])
    shape=matrix.shape
    print('Shape of the matrix is: ',shape)
    print('\n')
    scalar=5*matrix
    print('Scalar Matrix', scalar)
    transpose=matrix.T
    print('Transpose of the matrix: \n',transpose)

Shape of the matrix is:  (2, 2)


Scalar Matrix [[10 15]
 [ 5 20]]
Transpose of the matrix: 
 [[2 1]
 [3 4]]
Shape of the matrix is:  (2, 2)


Scalar Matrix [[ 5 10]
 [15 25]]
Transpose of the matrix: 
 [[1 3]
 [2 5]]
Shape of the matrix is:  (2, 2)


Scalar Matrix [[20  5]
 [10 30]]
Transpose of the matrix: 
 [[4 2]
 [1 6]]
Shape of the matrix is:  (2, 2)


Scalar Matrix [[15 25]
 [10 35]]
Transpose of the matrix: 
 [[3 2]
 [5 7]]
Shape of the matrix is:  (2, 2)


Scalar Matrix [[25 10]
 [20 40]]
Transpose of the matrix: 
 [[5 4]
 [2 8]]


In [109]:
# Matrix Addition
m1=np.array([[df6.loc[0,'m11'],df6.loc[0,'m12']],
           [df6.loc[0,'m21'],df6.loc[0,'m22']]])
m2=np.array([[df6.loc[1,'m11'],df6.loc[1,'m12']],
           [df6.loc[1,'m21'],df6.loc[1,'m22']]])
addition=m1+m2
print('Addition of two matrix is:\n',addition)

Addition of two matrix is:
 [[3 5]
 [4 9]]


In [111]:
# Question 12
determinant=np.linalg.det(matrix)
print('The determinant of the matrix is: ',determinant)

The determinant of the matrix is:  32.0


In [123]:
inverse=np.linalg.inv(matrix)
print('the inverse of the matrix is:\n',inverse)
'''
The matrix is a non singular matrix
'''

the inverse of the matrix is:
 [[ 0.25    -0.0625 ]
 [-0.125    0.15625]]


'\nThe matrix is a non singular matrix\n'

In [124]:
rank=np.linalg.matrix_rank(matrix)
print('The rank of the matrix is: ',rank)

The rank of the matrix is:  2


In [126]:
# Question 13
multiplication=m1@m2
print('The multiplication of 2 matrix is:\n',multiplication)
print('The shape of the resulting matrix is:',multiplication.shape)

The multiplication of 2 matrix is:
 [[11 19]
 [13 22]]
The shape of the resulting matrix is: (2, 2)


In [135]:
# Question 14
dot_product=np.dot(v1,v2)
print('The dot product of 2 vectors is:',dot_product)

The dot product of 2 vectors is: 17


In [138]:
# Question 15
df7=pd.read_excel('calculus_data.xlsx')
print(df7)

   ID   x
0   1   1
1   2   2
2   3   3
3   4   4
4   5   5
5   6   6
6   7   7
7   8   8
8   9   9
9  10  10


In [139]:
df7['y']=df7['x']**2
df7['Deravative']=np.gradient(df7['y'],df7['x'])
print(df7)

   ID   x    y  Deravative
0   1   1    1         3.0
1   2   2    4         4.0
2   3   3    9         6.0
3   4   4   16         8.0
4   5   5   25        10.0
5   6   6   36        12.0
6   7   7   49        14.0
7   8   8   64        16.0
8   9   9   81        18.0
9  10  10  100        19.0


In [140]:
# Question 16
df7['integration']=np.trapz(df7['y'],df7['x'])
print(df7)

   ID   x    y  Deravative  integration
0   1   1    1         3.0        334.5
1   2   2    4         4.0        334.5
2   3   3    9         6.0        334.5
3   4   4   16         8.0        334.5
4   5   5   25        10.0        334.5
5   6   6   36        12.0        334.5
6   7   7   49        14.0        334.5
7   8   8   64        16.0        334.5
8   9   9   81        18.0        334.5
9  10  10  100        19.0        334.5


C:\Users\Hp\AppData\Local\Temp\ipykernel_13804\2947640509.py:2: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  df7['integration']=np.trapz(df7['y'],df7['x'])
