In [1]:
import numpy as np

data = np.array([
    [170, 65, 20],
    [160, 55, 19],
    [180, 75, 22]
])

print(data)

[[170  65  20]
 [160  55  19]
 [180  75  22]]


In [2]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.shape)

(2, 3)


In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = A + B
print(result)

[[ 6  8]
 [10 12]]


In [4]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

result = 2 * matrix
print(result)

[[2 4]
 [6 8]]


In [5]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpose = matrix.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [7]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
import numpy as np

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
import numpy as np

A = np.array([[2, 4],
              [1, 2]])

det = np.linalg.det(A)

if det == 0:
    print("Singular Matrix")
else:
    print("Non-Singular Matrix")

Singular Matrix


In [10]:
import numpy as np

A = np.array([[1, 2],
              [2, 4]])

rank = np.linalg.matrix_rank(A)
print(rank)

1


In [3]:
import numpy as np
c=np.array([[1,2,3],
            [4,5,6],
            [1,2,3]])
shape=c.shape
print(shape)

(3, 3)


In [4]:
det=np.linalg.det(c)
print(det)

0.0


In [7]:
inverse=np.linalg.inv(c)
print(inverse)

LinAlgError: Singular matrix

In [8]:
rank=np.linalg.matrix_rank(c)
print(rank)

2
