In [1]:
import numpy as np
print(np.random.rand(3))

[0.19486396 0.51547082 0.07204107]


In [2]:
import numpy as np
print(np.random.randn(3))

[-0.44989919  0.20963998  0.40026684]


In [3]:
import numpy as np

arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[4 3 9]
 [2 5 8]]


In [6]:
import numpy as np

arr = [10, 20, 30, 40]
print(np.random.choice(arr, size=2))

[10 40]


In [7]:
import numpy as np

np.random.seed(42)
print(np.random.rand(2))

[0.37454012 0.95071431]


In [8]:
import numpy as np
uniform_vals = np.random.uniform(0, 1, size=4)
normal_vals = np.random.normal(0, 1, size=4)
print(uniform_vals)
print(normal_vals)

[0.73199394 0.59865848 0.15601864 0.15599452]
[ 1.57921282  0.76743473 -0.46947439  0.54256004]


In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[1:4])

30
[20 30 40]


In [10]:
import numpy as np

arr = np.array([100, 200, 300, 400])
indices = [0, 2]
print(arr[indices])

[100 300]


In [11]:
import numpy as np

arr = np.array([5, 10, 15, 20])
mask = arr > 10
print(arr[mask])

[15 20]


In [12]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[::2])
print(arr[::-1])

[1 3 5 7]
[8 7 6 5 4 3 2 1]


In [14]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1, :])
print(arr[:, 2])

[40 50 60]
[30 60 90]


In [15]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])
print(arr[arr % 4 == 0])

[4 8]


In [1]:
# Array Operation and manupilation
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * 2)

[5 7 9]
[2 4 6]


In [2]:
import numpy as np

arr = np.array([5, 10, 15])
print(arr > 7)
print((arr > 7) & (arr < 14))

[False  True  True]
[False  True False]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr.sum()

print(result)

15


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr.mean()

print(result)

3.0


In [5]:
import numpy as np

arr = np.array([8, 3, 15, 2, 10])
result = arr.min()

print(result)

2


In [6]:
import numpy as np

arr = np.array([8, 3, 15, 2, 10])
result = arr.max()

print(result)

15


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr.std()

print(result)

1.4142135623730951


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr.var()

print(result)

2.0


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [10]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)

(2, 3)


In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

2


In [12]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.size)

6


In [13]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flat = arr.ravel()
print(flat)

[1 2 3 4]


In [16]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)

[1 2 3 4]


In [17]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.hstack((a, b)))

[1 2 3 4]


In [18]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))

[[1 2]
 [3 4]]


In [19]:
import numpy as np

a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]]
[[1 2 3 4]]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
parts = np.split(arr, 3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.hsplit(arr, 3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [22]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.vsplit(arr, 3))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
