In [1]:
import numpy as np
print(np.random.rand(3))

[0.19486396 0.51547082 0.07204107]


In [2]:
import numpy as np
print(np.random.randn(3))

[-0.44989919  0.20963998  0.40026684]


In [3]:
import numpy as np

arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[4 3 9]
 [2 5 8]]


In [6]:
import numpy as np

arr = [10, 20, 30, 40]
print(np.random.choice(arr, size=2))

[10 40]


In [7]:
import numpy as np

np.random.seed(42)
print(np.random.rand(2))

[0.37454012 0.95071431]


In [8]:
import numpy as np
uniform_vals = np.random.uniform(0, 1, size=4)
normal_vals = np.random.normal(0, 1, size=4)
print(uniform_vals)
print(normal_vals)

[0.73199394 0.59865848 0.15601864 0.15599452]
[ 1.57921282  0.76743473 -0.46947439  0.54256004]


In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[1:4])

30
[20 30 40]


In [10]:
import numpy as np

arr = np.array([100, 200, 300, 400])
indices = [0, 2]
print(arr[indices])

[100 300]


In [11]:
import numpy as np

arr = np.array([5, 10, 15, 20])
mask = arr > 10
print(arr[mask])

[15 20]


In [12]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[::2])
print(arr[::-1])

[1 3 5 7]
[8 7 6 5 4 3 2 1]


In [14]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1, :])
print(arr[:, 2])

[40 50 60]
[30 60 90]


In [15]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])
print(arr[arr % 4 == 0])

[4 8]
