In [1]:
import numpy as np
arr=np.array([40,np.nan,50,np.inf])
print(np.isnan(arr))
print(np.isinf(arr))

[False  True False False]
[False False False  True]


In [4]:
import numpy as np
arr = np.array([1, np.nan, 3, np.inf])
arr[np.isnan(arr)] = 0
arr[np.isinf(arr)] = 0
print(arr)

[1. 0. 3. 0.]


In [5]:
import numpy as np
arr = np.array([1, np.nan, 5, np.inf, 7])
clean_arr = arr[~np.isnan(arr)]
clean_arr = clean_arr[~np.isinf(clean_arr)]
print(clean_arr)

[1. 5. 7.]


In [11]:
import numpy as np
arr = np.array([1, 2, 3])
copy_arr = arr.copy()
view_arr = arr.view()
view_arr[0] = 10
print(copy_arr)
print(view_arr)

[1 2 3]
[10  2  3]


In [12]:
import numpy as np
arr = np.array([5, 6, 7])
v = arr.view()
v[1] = 100
print(arr)

[  5 100   7]


In [14]:
import numpy as np
big = np.arange(1_000_000)
v = big.view()   # uses no extra memory
c = big.copy()   # duplicates 1 million elements
print(v)
print(c)

[     0      1      2 ... 999997 999998 999999]
[     0      1      2 ... 999997 999998 999999]
