In [18]:
import numpy as np
import sys
list_obj=[1,2,3,4,5,6]
arr_obj=np.array([1,2,3,4])
print(sys.getsizeof(list_obj))
print(arr_obj.nbytes)

104
32


In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = 2
result = a * b
print(result)

[2 4 6]


In [8]:
import numpy as np
data = np.array([1, 2, 3])
np.save('my_array.npy', data)
load_data=np.load('my_array.npy')
print(load_data)

[1 2 3]


In [11]:
import numpy as np
data = np.array([[1, 2], [3, 4]])
np.savetxt('data.txt', data, delimiter=',')


In [12]:
import numpy as np
arr = np.genfromtxt('data.txt', delimiter=',')
print(arr)

[[1. 2.]
 [3. 4.]]


In [13]:
import numpy as np
import pandas as pd
arr = np.array([[10, 20], [30, 40]])
df = pd.DataFrame(arr, columns=["A", "B"])
print(df)

    A   B
0  10  20
1  30  40


In [14]:
import numpy as np
time = np.arange(0, 10, 0.1)
position = 5 * time ** 2
print(position)

[0.0000e+00 5.0000e-02 2.0000e-01 4.5000e-01 8.0000e-01 1.2500e+00
 1.8000e+00 2.4500e+00 3.2000e+00 4.0500e+00 5.0000e+00 6.0500e+00
 7.2000e+00 8.4500e+00 9.8000e+00 1.1250e+01 1.2800e+01 1.4450e+01
 1.6200e+01 1.8050e+01 2.0000e+01 2.2050e+01 2.4200e+01 2.6450e+01
 2.8800e+01 3.1250e+01 3.3800e+01 3.6450e+01 3.9200e+01 4.2050e+01
 4.5000e+01 4.8050e+01 5.1200e+01 5.4450e+01 5.7800e+01 6.1250e+01
 6.4800e+01 6.8450e+01 7.2200e+01 7.6050e+01 8.0000e+01 8.4050e+01
 8.8200e+01 9.2450e+01 9.6800e+01 1.0125e+02 1.0580e+02 1.1045e+02
 1.1520e+02 1.2005e+02 1.2500e+02 1.3005e+02 1.3520e+02 1.4045e+02
 1.4580e+02 1.5125e+02 1.5680e+02 1.6245e+02 1.6820e+02 1.7405e+02
 1.8000e+02 1.8605e+02 1.9220e+02 1.9845e+02 2.0480e+02 2.1125e+02
 2.1780e+02 2.2445e+02 2.3120e+02 2.3805e+02 2.4500e+02 2.5205e+02
 2.5920e+02 2.6645e+02 2.7380e+02 2.8125e+02 2.8880e+02 2.9645e+02
 3.0420e+02 3.1205e+02 3.2000e+02 3.2805e+02 3.3620e+02 3.4445e+02
 3.5280e+02 3.6125e+02 3.6980e+02 3.7845e+02 3.8720e+02 3.9605

In [15]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
import numpy as np
image = np.array([[0, 255], [128, 64]])
print(image[0, 1])

255


In [17]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(data))
print("Std Dev:", np.std(data))

Mean: 3.0
Std Dev: 1.4142135623730951
