In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])
result = np.where(arr > 25, 'High', 'Low')
print(result)

['Low' 'Low' 'High' 'High']


In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
conditions = [arr < 15, arr < 35]
choices = ['Low', 'Medium']
result = np.select(conditions, choices, default='High')
print(result)

['Low' 'Medium' 'Medium' 'High']


In [3]:
import numpy as np

arr = np.array([10, 20, 10, 30, 20])
print(np.unique(arr))

[10 20 30]


In [4]:
import numpy as np

arr = np.array([0, 0, 5])
print(np.any(arr > 0))

True


In [5]:
import numpy as np

arr = np.array([1, 2, 3])
print(np.all(arr > 0))

True


In [6]:
# Sorting and searching
import numpy as np

arr = np.array([30, 10, 20, 10])
print(np.sort(arr))

[10 10 20 30]


In [7]:
import numpy as np

arr = np.array([30, 10, 20])
print(np.argsort(arr))

[1 2 0]


In [8]:
import numpy as np
arr = np.array([3, 8, 1, 6])
print(arr.argmax())
print(arr.argmin())

1
2
