In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [2]:
import numpy as np

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2], [3, 4]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1D)
print(arr2D)
print(arr3D)

[1 2 3]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

(2, 3)
2
int64
6


In [4]:
import numpy as np

arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
import numpy as np

arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


In [7]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [11]:
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
import numpy as np

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np

arr = np.diag([1, 2, 3])
print(arr)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
