In [7]:
# Task1
import numpy as np
student1=np.array([60,70,80,90,100])
print(f"The array containing marks of 5 students is: {student1}")
student2=np.array([[60,70,80],[80,90,100]])
print(f"The array repersenting marks of 2 students in 3 subjects is:\n {student2}")
student3=np.array([[[60,65,70],[40,45,50]] ,[[75,80,85],[90,95,100]]])
print(f"The array representing marks of 2 classes, each with 2 students and 3 subjects is:\n {student3}")

The array containing marks of 5 students is: [ 60  70  80  90 100]
The array repersenting marks of 2 students in 3 subjects is:
 [[ 60  70  80]
 [ 80  90 100]]
The array representing marks of 2 classes, each with 2 students and 3 subjects is:
 [[[ 60  65  70]
  [ 40  45  50]]

 [[ 75  80  85]
  [ 90  95 100]]]


In [8]:
# Task2
arr=np.array([[1,2,3],[4,5,6]])
print(f"The array are:\n {arr}")
print(f"The size of the matrix is: {arr.shape}")
print(f"The dimension of the matrix is: {arr.ndim}")
print(f"The data type of the matrix is : {arr.dtype}")
print(f"The number of elements inside the matrix is: {arr.size}")

The array are:
 [[1 2 3]
 [4 5 6]]
The size of the matrix is: (2, 3)
The dimension of the matrix is: 2
The data type of the matrix is : int64
The number of elements inside the matrix is: 6


In [9]:
# Task 3
arr1=np.zeros((3,4))
print(f"The matrix for displaying only zero is:\n {arr1}")
arr2=np.ones((2,3))
print(f"The matrix for displaying only ones is:\n {arr2}")
arr3=np.full((3,3),5)
print(f"The matrix for displaying only 5 is: \n {arr3}")

The matrix for displaying only zero is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The matrix for displaying only ones is:
 [[1. 1. 1.]
 [1. 1. 1.]]
The matrix for displaying only 5 is: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [12]:
# Task 4
arr4=np.arange(10,50,10)
print(f"The formed array from 10 to 50 with step 10 is :{arr4}")
arr5=np.linspace(0,100,5)
print(f"The 5 evenly spaced array values between 0 and 100 are: {arr5}")

The formed array from 10 to 50 with step 10 is :[10 20 30 40]
The 5 evenly spaced array values between 0 and 100 are: [  0.  25.  50.  75. 100.]


In [17]:
# Task 5
arr5=np.eye(4)
print(f"The 4 x 4 identity matrix is :\n {arr5}")
arr6=np.diag([10,20,30,40])
print(f"The diagonal matrix for showing the array\"[10,20,30,40]\" is : \n{arr6}")

The 4 x 4 identity matrix is :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The diagonal matrix for showing the array"[10,20,30,40]" is : 
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
