In [1]:
# Task 1
import numpy as np
print(f"The 5 random numbers between 0 and 1 is:\n{np.random.rand(5)}")
print(f"The 5 random numbers between 0 and 1 using normal distribution is:\n{np.random.randn(5)}")

The 5 random numbers between 0 and 1 is:
[0.90958853 0.95287444 0.08550507 0.30278613 0.47851816]
The 5 random numbers between 0 and 1 using normal distribution is:
[-0.2927342  -0.41292889 -1.05392618  0.91269765 -0.52619513]


In [2]:
# Task 2
arr=np.random.randint(35,100,(3,4))
print(f"The 3×4 array of random integers between 35 and 100\n{arr}")

The 3×4 array of random integers between 35 and 100
[[64 86 80 35]
 [59 59 60 76]
 [51 35 40 99]]


In [3]:
# Task 3
arr=[101, 102, 103, 104, 105]
print(f"The randomly selected students is:{np.random.choice(arr,size=2)}")


The randomly selected students is:[105 101]


In [4]:
# Task 4
np.random.seed(10)
print(f"Generating 3 random values{np.random.rand(3)}")

Generating 3 random values[0.77132064 0.02075195 0.63364823]


In [12]:
# Task 5
arr=np.array([10, 20, 30, 40, 50, 60])
print(f"The 3rd element in the array is: {arr[2]}")
print(f"Elements from index 1 to 4 is: {arr[1:4]}")
print(f"Element from the last array is: {arr[-1]}")
print(f"To print every second element in an array is: {arr[::2]}")
print(f"Reversing every element in an array is: {arr[::-1]}")

The 3rd element in the array is: 30
Elements from index 1 to 4 is: [20 30 40]
Element from the last array is: 60
To print every second element in an array is: [10 30 50]
Reversing every element in an array is: [60 50 40 30 20 10]
