In [6]:
# Task 1
import numpy as np
marks_term1=np.array([60,70,80,90])
marks_term2=np.array([65,75,85,95])
total_marks=marks_term1+marks_term2
print(f"The total marks in both terms is: {total_marks}")
print(f"The difference between two terms are: {marks_term1-marks_term2}")
print(f"The increased percentage in term 1 is: {marks_term1*1.05}")
print(f"The increased percentage in term 2 is: {marks_term2*1.05}")

The total marks in both terms is: [125 145 165 185]
The difference between two terms are: [-5 -5 -5 -5]
The increased percentage in term 1 is: [63.  73.5 84.  94.5]
The increased percentage in term 2 is: [68.25 78.75 89.25 99.75]


In [10]:
# Task 2
print(f"Marks which is greater than 150 is: {total_marks>150}")
print(f"The marks which is between 140 and 170 is: {(total_marks>140)&(total_marks<170)}")

Marks which is greater than 150 is: [False False  True  True]
The marks which is between 140 and 170 is: [False  True  True False]


In [16]:
# Task 3
print(f"The sum of all elements in total marks is: {total_marks.sum()}")
print(f"The average of total marks is: {total_marks.mean()}")
print(f"The maximum value in total marks is: {total_marks.max()}")
print(f"The minimum value in total marks is: {total_marks.min()}")
print(f"The standard deviation of total marks is: {total_marks.std()}")

The sum of all elements in total marks is: 620
The average of total marks is: 155.0
The maximum value in total marks is: 185
The minimum value in total marks is: 125
The standard deviation of total marks is: 22.360679774997898


In [25]:
# Task 4
marks=np.array([[70,80,90],[60,75,85]])
print(f"The marks are:\n{marks}")
print(f"The column wise sum is:\n {marks.sum(axis=0)}")
print(f"The row wise mean is:\n {marks.mean(axis=1)}")

The marks are:
[[70 80 90]
 [60 75 85]]
The column wise sum is:
 [130 155 175]
The row wise mean is:
 [80.         73.33333333]


In [35]:
# Task 5
arr=np.array([1,2,3,4,5,6])
print(f"The shape of the array is: {arr.shape}")
print(f"The dimension of the array is: {arr.ndim}D")
print(f"The number of elements inside the array is: {arr.size}")
print(f"The data type of the array is: {arr.dtype}")
print(f"Converting the array to 2 X 3 array:\n{arr.reshape(2,3)}")
print(f"Converting back to 1D:\n{arr.ravel()}")

The shape of the array is: (6,)
The dimension of the array is: 1D
The number of elements inside the array is: 6
The data type of the array is: int64
Converting the array to 2 X 3 array:
[[1 2 3]
 [4 5 6]]
Converting back to 1D:
[1 2 3 4 5 6]
