In [8]:
# Task 1
import numpy as np
values=np.random.rand(10)
print(f"The randomly generated values is :\n{values}")
present_values=values>0.5
print("The present values are",values[present_values])

The randomly generated values is :
[0.92493948 0.10716433 0.0326422  0.93247222 0.60173997 0.38295931
 0.59028666 0.1179535  0.5185337  0.06522236]
The present values are [0.92493948 0.93247222 0.60173997 0.59028666 0.5185337 ]


In [19]:
# Task 2
score=np.random.randint(0,101,15)
print("The scores are",score)
greater=score>60
print("The score greater than 60 is:",score[greater])
print("The score which is divisible by 5 is",score[score%5==0])

The scores are [ 71  73  44  30  85  43  21  91  68  24  55  21 100  68  25]
The score greater than 60 is: [ 71  73  85  91  68 100  68]
The score which is divisible by 5 is [ 30  85  55 100  25]


In [21]:
# Task 3
arr=np.array([100,200,300,400,500])
indices=[0,2,4]
print("The fancy element are:",arr[indices])

The fancy element are: [100 300 500]


In [32]:
# Task 4
arr=np.random.randint(1,50,(4,4))
print("The randomly generated array are:\n",arr)
print("The entire second row is:",arr[1,:])
print("The entire third column is",arr[:,2])

The randomly generated array are:
 [[35 40 38 44]
 [33 34 10 49]
 [42 42 19 10]
 [35 17  1 28]]
The entire second row is: [33 34 10 49]
The entire third column is [38 10 19  1]


In [33]:
# Task 5
uniform_val=np.random.uniform(0,1,size=5)
normal_val=np.random.normal(0,1,size=5)
print("The uniform values are ",uniform_val)
print("The normal values are ",normal_val)

The uniform values are  [0.42773662 0.50412831 0.39208814 0.73580457 0.41953938]
The normal values are  [ 1.04982355 -1.42909921 -1.48969329  0.98824399 -1.46460838]
