In [13]:
# Task 1
import numpy as np
monthly_sales=np.array([200,400,600,800,1000,1200,1400,1600,1800,2000,2200,2400])
print(f"The monthly sales are {monthly_sales}")
reshaped=monthly_sales.reshape(3,4)
print(f"Reshaping the monthly sales to 3 x 4 array is:\n{reshaped}")


The monthly sales are [ 200  400  600  800 1000 1200 1400 1600 1800 2000 2200 2400]
Reshaping the monthly sales to 3 x 4 array is:
[[ 200  400  600  800]
 [1000 1200 1400 1600]
 [1800 2000 2200 2400]]


In [14]:
# Task 2
print(f"Converting back to 1D using ravel: {reshaped.ravel()}")
print(f"Converting back to 1D using flatten: {reshaped.flatten()}")

Converting back to 1D using ravel: [ 200  400  600  800 1000 1200 1400 1600 1800 2000 2200 2400]
Converting back to 1D using flatten: [ 200  400  600  800 1000 1200 1400 1600 1800 2000 2200 2400]


In [17]:
# Task 3
dept1=np.array([100,200,300])
dept2=np.array([400,500,600])
print(f"Combining two arrays horizontally: {np.hstack((dept1,dept2))}")
print(f"Combining two arrays vertically:\n{np.vstack((dept1,dept2))}")

Combining two arrays horizontally: [100 200 300 400 500 600]
Combining two arrays vertically:
[[100 200 300]
 [400 500 600]]


In [22]:
# Task 4
a=np.array([[1,2]])
b=np.array([[3,4]])
print(f"Concatenating row wise:\n{np.concatenate((a,b),axis=0)}")
print(f"Concatenating column wise:\n{np.concatenate((a,b),axis=1)}")

Concatenating row wise:
[[1 2]
 [3 4]]
Concatenating column wise:
[[1 2 3 4]]


In [24]:
# Task 5
arr=np.array([10,20,30,40,50,60])
parts=np.split(arr,3)
print(f"Array splitted using 3 equal parts is: {parts}")

Array splitted using 3 equal parts is: [array([10, 20]), array([30, 40]), array([50, 60])]


In [30]:
# Task 5.1
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"The splitted array using hsplit is:\n{np.hsplit(arr1,3)}")
print(f"The splitted array using vsplit is:\n{np.vsplit(arr1,3)}")

The splitted array using hsplit is:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
The splitted array using vsplit is:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
