In [14]:
# Task 1
import numpy as np
arr1=np.arange(101,121)
print(f"The array to be printed is :\n{arr1}")
print(f"The shape of the matrix is :{arr1.shape}")
print(f"The size of the matrix is :{arr1.size}")
print(f"The data type of the matrix is : {arr1.dtype}")

The array to be printed is :
[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
The shape of the matrix is :(20,)
The size of the matrix is :20
The data type of the matrix is : int64


In [16]:
# Task 2
arr2=np.full((5,5),1)
print(f"The 5 x 5 matrix to be filled with 1 is:\n {arr2}")
print(f"The dimension of the array is: {arr2.ndim}")

The 5 x 5 matrix to be filled with 1 is:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
The dimension of the array is: 2


In [19]:
# Task 3
arr3=np.zeros((4,3))
print(f" 4×3 array of zeros to represent initial scores of 4 students in 3 subjects:\n {arr3}")

 4×3 array of zeros to represent initial scores of 4 students in 3 subjects:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# Task 4
arr4=np.linspace(0,100,6)
print(f"The 6 evenly spaced values between 0 and 100 is:\n {arr4}")
# Linspace can be used for scientifc computing and data visualisation

The 6 evenly spaced values between 0 and 100 is:
 [  0.  20.  40.  60.  80. 100.]


In [22]:
# Task 5
arr5=np.eye(5)
print(f"The identity matrix with 5 x 5 size is:\n {arr5}")
arr6=np.diag([2,4,6,8,10])
print(f"The diagonal matrix with the number given is:\n {arr6}")

The identity matrix with 5 x 5 size is:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The diagonal matrix with the number given is:
 [[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]
