In [8]:
# Part-1
import numpy as np
daily_sales=np.array([250.75, 300.40, 275.60, 400.90, 150.30, 500.50, 350.80])
print(f"The daily sales are:\n{daily_sales}")
total_weekly_sales=np.sum(daily_sales)
print(f"The daily total weekly sales is: {total_weekly_sales}")
mean_sales=np.mean(daily_sales)
print(f"The average for daily sales is: {mean_sales}")
median_sales=np.median(daily_sales)
print(f"The median sales are: {median_sales}")
variation=np.std(daily_sales)
print(f"The varaiation in daily sales is: {variation}")
minimum=np.min(daily_sales)
print(f"The minimum values of daily sales is: {minimum}")
maximum=np.max(daily_sales)
print(f"The maximum value in daily sales is: {maximum}")

The daily sales are:
[250.75 300.4  275.6  400.9  150.3  500.5  350.8 ]
The daily total weekly sales is: 2229.25
The average for daily sales is: 318.4642857142857
The median sales are: 300.4
The varaiation in daily sales is: 104.2019766548385
The minimum values of daily sales is: 150.3
The maximum value in daily sales is: 500.5


In [12]:
# Part-2
floor=np.floor(daily_sales)
print(f"The floor values for daily sales is: {floor}")
ceil=np.ceil(daily_sales)
print(f"The ceil values for daily sales is: {ceil}")
rounding=np.round(daily_sales)
print(f"The rounded values for daily sales is: {rounding}")
arr=np.array([1,2,3])
expo=np.exp(arr)
print(f"The exponential growth is: {expo}")

The floor values for daily sales is: [250. 300. 275. 400. 150. 500. 350.]
The ceil values for daily sales is: [251. 301. 276. 401. 151. 501. 351.]
The rounded values for daily sales is: [251. 300. 276. 401. 150. 500. 351.]
The exponential growth is: [ 2.71828183  7.3890561  20.08553692]


In [13]:
# Part-3
cumilative_sum=np.cumsum(daily_sales)
print(f"The cumilative sum of daily sales is: {cumilative_sum}")

The cumilative sum of daily sales is: [ 250.75  551.15  826.75 1227.65 1377.95 1878.45 2229.25]


In [22]:
# Part-4
a=np.array([[2,1],[3,4]])
b=np.array([[1,2],[5,6]])
multiplication=a@b
print(f"The product of two matrix is:\n{multiplication}")
determinant=np.linalg.det(a)
print(f"The determinant of matrix \"a\" is: {determinant}")
inverse=np.linalg.inv(a)
print(f"The inverse of matrix \"a\" is:\n{inverse}")
values,vectors=np.linalg.eig(a)
print(f"The eigen values of matrix A is:\n{values}")
print(f"The eigen vectors of matrix A is:\n{vectors}")


The product of two matrix is:
[[ 7 10]
 [23 30]]
The determinant of matrix "a" is: 5.000000000000001
The inverse of matrix "a" is:
[[ 0.8 -0.2]
 [-0.6  0.4]]
The eigen values of matrix A is:
[1. 5.]
The eigen vectors of matrix A is:
[[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]


In [24]:
# Part-5
x=np.array([[2,1],[3,4]])
y=np.array([5,11])
result=np.linalg.solve(a,b)
print(f"The solved linear equation is:\n{result}")

The solved linear equation is:
[[-0.2  0.4]
 [ 1.4  1.2]]
