In [ ]:
# Question 1
import numpy as np
import pandas as pd
noise=pd.read_csv("noise_data.csv")
print(f"The noise dataset is:\n {noise}")
sales=pd.read_csv("sales_data.csv")
print(f"The sales dataset is:\n {sales}")
customer=pd.read_csv("customer_data.csv")
print(f"The customer dataset is:\n {customer}")
print(f"The shape of the sales dataset is: {sales.shape}")
print(f"The shape of the noise dataset is: {noise.shape}")
print(f"The shape of the customer dataset is: {customer.shape}")
print(f"The number of elements in sales dataset is: {sales.size}")
print(f"The number of elemnts in noise dataset is: {noise.size}")
print(f"The number of elemnts in customer dataset is : {customer.size}")
print(f"The dimension of sales dataset is: {sales.ndim}")
print(f"The dimension of noise dataset is: {noise.ndim}")
print(f"The dimension of customer dataset is: {customer.ndim}")
print(f"The data type of sales dataset is:\n{sales.dtypes}")
print(f"The data type of noise dataset is:\n{noise.dtypes}")
print(f"The data type of customer datset is:\n{customer.dtypes}")

In [2]:
# Question 2
arr=np.zeros((3,3))
print(f"The 3 X 3 array filled with zeros:\n{arr}")
arr2=np.ones((3,3))
print(f"The 3 X 3 array filled with ones:\n {arr2}")
arr3=np.full((3,3),7)
print(f"The 3 X3 array filled with 7:\n {arr3}")
arr4=np.arange(0,10,2)
print(f"The sequence from 0 to 10 with step 2 is:\n {arr4}")
arr5=np.linspace(0,1,5)
print(f"5 values evenly spaced between 0 and 1 is:\n {arr5}")
arr6=np.eye(3)
print(f"Identity matrix:\n {arr6}")
arr7=np.diag([1,2,3])
print(f"The diagonal element filled with 1,2,3 is:\n {arr7}")

The 3 X 3 array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The 3 X 3 array filled with ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The 3 X3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
The sequence from 0 to 10 with step 2 is:
 [0 2 4 6 8]
5 values evenly spaced between 0 and 1 is:
 [0.   0.25 0.5  0.75 1.  ]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
The diagonal element filled with 1,2,3 is:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
# Question3
data1=np.random.rand(3)
print(f"The data sets are:\n {data1}")
average=np.mean(data1)
print(f"The average of the data is: {average}")
data2=np.random.randn(3)
print(f"The datasets are:\n {data2}")
average2=np.mean(data2)
print(f"The average value for dataset 2 is: {average2}")

The data sets are:
 [0.77011557 0.38509084 0.45035618]
The average of the data is: 0.5351875293420751
The datasets are:
 [-0.79783232  0.81635718 -0.97531063]
The average value for dataset 2 is: -0.3189285909237391


In [4]:
# Question 4
print(f"The first five rows for customer dataset is:\n{customer[:5]}")
print(f"To display the last rows for customer dataset is:\n {customer[-1:]}")
customer2=np.genfromtxt("customer_data.csv",delimiter=',')
print(f"To display the first column of customer dataset is:\n {customer2[:,1]}")
print(f"To display every second row of customer dataset is:\n {customer2[::2]}")
print(f"To display rows 0–4 and columns 1–2:\n {customer2[0:5,1:3]}")
indices=[1,5,10]
print(f"To select specific rows like 1, 5, and 10:\n {customer2[indices]}")

The first five rows for customer dataset is:
  Age,Salary,Spending_Score,Purchase_Count,Tenure
0                                  56,46,32,25,38
1                                  56,36,40,28,28
2                                  41,53,57,41,20
3                                  39,19,41,47,55
4                                  19,38,50,29,39
To display the last rows for customer dataset is:
     Age,Salary,Spending_Score,Purchase_Count,Tenure
999                                  32,36,52,34,52
To display the first column of customer dataset is:
 [nan 46. 36. ... 23. 31. 36.]
To display every second row of customer dataset is:
 [[nan nan nan nan nan]
 [nan 36. 40. 28. nan]
 [nan 19. 41. 47. nan]
 ...
 [nan 23. 22. 39. nan]
 [nan 23. 23. 35. nan]
 [nan 36. 52. 34. nan]]
To display rows 0–4 and columns 1–2:
 [[nan nan]
 [46. 32.]
 [36. 40.]
 [53. 57.]
 [19. 41.]]
To select specific rows like 1, 5, and 10:
 [[nan 46. 32. 25. nan]
 [nan 38. 50. 29. nan]
 [nan 24. 25. 52. nan]]


In [10]:
#Question 5
result1=customer2[customer2[:,0]>30]
print(f"Get rows where first column is greater than 30:\n {result1}")
mask = (customer2[:, 0] > 30) & (customer2[:, 1] > 30)
print(f"Get rows where first column > 30 AND second column > 30:\n {customer2[mask]}")

Get rows where first column is greater than 30:
 []
Get rows where first column > 30 AND second column > 30:
 []


In [22]:
# Question 6
multiply=customer2*2
print(f"Multiplying all the dataset value to 2 is:\n {multiply}")

    

Multiplying all the dataset value to 2 is:
 [[ nan  nan  nan  nan  nan]
 [ nan  92.  64.  50.  nan]
 [ nan  72.  80.  56.  nan]
 ...
 [ nan  46.  46.  70.  nan]
 [ nan  62.  62.  60.  nan]
 [ nan  72. 104.  68.  nan]]


In [23]:
# Question 5.1 
# Using for loop
for custom in customer2:
    result=custom*2
    print(result)

[nan nan nan nan nan]
[nan 92. 64. 50. nan]
[nan 72. 80. 56. nan]
[ nan 106. 114.  82.  nan]
[nan 38. 82. 94. nan]
[ nan  76. 100.  58.  nan]
[ nan  88. 118.  90.  nan]
[ nan  40. 108.  48.  nan]
[ nan 112.  70.  42.  nan]
[nan 52. 86. 38. nan]
[ nan  48.  50. 104.  nan]
[ nan 106. 114.  42.  nan]
[ nan 118.  42.  92.  nan]
[ nan 102.  54. 106.  nan]
[nan 64. 50. 62. nan]
[nan 76. 66. 70. nan]
[ nan  84. 116.  92.  nan]
[nan 84. 48. 52. nan]
[nan 50. 82. 56. nan]
[ nan 104. 104. 100.  nan]
[ nan 112. 116.  90.  nan]
[ nan  50.  58. 102.  nan]
[ nan  82. 108. 104.  nan]
[ nan  88. 104.  36.  nan]
[nan 62. 40. 36. nan]
[ nan  62. 112.  88.  nan]
[ nan  64.  86. 118.  nan]
[ nan 112.  98.  42.  nan]
[ nan  80. 112.  64.  nan]
[nan 60. 98. 48. nan]
[ nan  38. 118.  46.  nan]
[nan 74. 94. 56. nan]
[ nan 112. 100.  36.  nan]
[ nan 116.  40. 112.  nan]
[ nan  88.  52. 108.  nan]
[nan 82. 64. 98. nan]
[ nan 116.  58. 112.  nan]
[ nan 108.  68.  38.  nan]
[ nan  80. 108.  98.  nan]
[nan 72. 38.

In [24]:
# Question 6
row_sum=np.sum(customer2,axis=0)
print(f"The row sum is:\n {row_sum}")
col_avg=np.mean(customer2,axis=1)
print(f"The col sum is:\n {col_avg}")

The row sum is:
 [nan nan nan nan nan]
The col sum is:
 [nan nan nan ... nan nan nan]


In [44]:
# Question 7
reshaped=customer2.reshape((65,77))
print(f"The reshaped dataset is:\n {reshaped}")
single=customer2.ravel()
print(f"Converting to 1D we get:\n {single}")
print("Conactinating two datasets vertically\n",np.vstack((customer,sales)))
parts=np.split(sales,5)
print("Split the data into 5 equal parts",parts)

The reshaped dataset is:
 [[nan nan nan ... nan nan 38.]
 [33. 35. nan ... 19. 59. 23.]
 [nan nan 37. ... 58. nan nan]
 ...
 [nan nan 51. ... 55. nan nan]
 [33. 29. 48. ... nan 26. 19.]
 [18. nan nan ... 52. 34. nan]]
Converting to 1D we get:
 [nan nan nan ... 52. 34. nan]
Conactinating two datasets vertically
 [['56,46,32,25,38']
 ['56,36,40,28,28']
 ['41,53,57,41,20']
 ...
 ['1,369,504,913,598,560,000,000,000,000,000,000,000,000,000,000']
 ['85,652,406,945,099,900,000,000,000,000,000,000,000,000,000,000']
 ['334,322,819,741,319,000,000,000,000,000,000,000,000,000,000,000']]
Split the data into 5 equal parts [                           0,1,2,3,4,5,6,7,8,9,10,11
0  203,917,359,990,819,000,000,000,000,000,000,00...
1  9,443,205,671,234,000,000,000,000,000,000,000,...
2  498,739,543,658,987,000,000,000,000,000,000,00...
3  53,447,219,416,629,400,000,000,000,000,000,000...
4  281,087,448,169,175,000,000,000,000,000,000,00...
5  15,476,109,707,465,200,000,000,000,000,000,000...
6  3,822,50

C:\Users\vaibh\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [47]:
#  Question 8
sort=np.sort(customer2)
print("The sorted dataset is\n",sort)
maximum=np.argmax(customer2)
print("The position of maximum value is\n",maximum)
minimum=np.argmin(customer2)
print("The minimum value is\n",minimum)

The sorted dataset is
 [[nan nan nan nan nan]
 [25. 32. 46. nan nan]
 [28. 36. 40. nan nan]
 ...
 [23. 23. 35. nan nan]
 [30. 31. 31. nan nan]
 [34. 36. 52. nan nan]]
The position of maximum value is
 0
The minimum value is
 0


In [50]:
# Question 9
dataset=np.array([20,40,60,80,100])
display=np.where(dataset>30,'High','Low')
print(display)

['Low' 'High' 'High' 'High' 'High']


In [65]:
# Question 10
load=np.genfromtxt('sales_data.csv',delimiter=',',skip_header=1,invalid_raise=False) # invalid_raise=False to skip the inconsistent rows
print("The loaded dataset:\n",load)
average=np.nanmean(load) # nanmean is used instead of mean is because inconsistent rows get filled with NaN 
print("The average is",average)

The loaded dataset:
 [[ nan 917. 359. 990. 819.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 443. 205. 671. 234.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 739. 543. 658. 987.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 447. 219. 416. 629. 400.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan  87. 448. 169. 175.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 476. 109. 707. 465. 200.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 822. 500. 673. 635. 150.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 906. 907.  10. 725. 730.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 463.  31. 307. 121. 100.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 896. 498. 407. 800.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 192. 696. 297. 555.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  nan]
 [ nan 868. 722. 853.  65. 400.   0.   0.   

C:\Users\vaibh\AppData\Local\Temp\ipykernel_21864\4059711967.py:2: ConversionWarning: Some errors were detected !
    Line #14 (got 15 columns instead of 16)
    Line #21 (got 15 columns instead of 16)
    Line #31 (got 15 columns instead of 16)
  load=np.genfromtxt('sales_data.csv',delimiter=',',skip_header=1,invalid_raise=False) # invalid_raise=False to skip the inconsistent rows


In [67]:
# Question 11
median=np.nanmedian(load)
print("The median is:",median)
standard=np.nanstd(load)
print("The standard deviation is: ",standard)
varience=np.nanvar(load)
print("The varience is: ",varience)
cum_sum=np.nancumsum(load)
print("The cum sum is: \n",cum_sum)

The median is: 0.0
The standard deviation is:  297.99119229596243
The varience is:  88798.75068596927
The cum sum is: 
 [     0.    917.   1276.   2266.   3085.   3085.   3085.   3085.   3085.
   3085.   3085.   3085.   3085.   3085.   3085.   3085.   3085.   3528.
   3733.   4404.   4638.   4638.   4638.   4638.   4638.   4638.   4638.
   4638.   4638.   4638.   4638.   4638.   4638.   5377.   5920.   6578.
   7565.   7565.   7565.   7565.   7565.   7565.   7565.   7565.   7565.
   7565.   7565.   7565.   7565.   8012.   8231.   8647.   9276.   9676.
   9676.   9676.   9676.   9676.   9676.   9676.   9676.   9676.   9676.
   9676.   9676.   9763.  10211.  10380.  10555.  10555.  10555.  10555.
  10555.  10555.  10555.  10555.  10555.  10555.  10555.  10555.  10555.
  11031.  11140.  11847.  12312.  12512.  12512.  12512.  12512.  12512.
  12512.  12512.  12512.  12512.  12512.  12512.  12512.  13334.  13834.
  14507.  15142.  15292.  15292.  15292.  15292.  15292.  15292.  15292.
  15

In [78]:
# Question 12
matrix=np.array([[1,2],[3,4]])
solve=np.array([5,6])
print("The matrix is:\n",matrix)
answer=matrix@matrix
print("The product of two matrix is:\n",answer)
det=np.linalg.det(matrix)
print("The determinant of the matrix is:",det)
inv=np.linalg.inv(matrix)
print("The inverse of the matrix is:\n",inv)
linear=np.linalg.solve(matrix,solve)
print("The solved linear equation is:\n",linear)

The matrix is:
 [[1 2]
 [3 4]]
The product of two matrix is:
 [[ 7 10]
 [15 22]]
The determinant of the matrix is: -2.0000000000000004
The inverse of the matrix is:
 [[-2.   1. ]
 [ 1.5 -0.5]]
The solved linear equation is:
 [-4.   4.5]


In [84]:
# Question 13
print("To display wheather there is isnan in noise dataset:\n",np.isnan(noise))
print("To display wheather there is isinf in noise dataset:\n",np.isinf(noise))
noise[np.isinf(noise)]=5
print(noise)

To display wheather there is isnan in noise dataset:
      Noise
0    False
1    False
2    False
3    False
4    False
..     ...
462  False
463  False
464  False
465  False
466  False

[467 rows x 1 columns]
To display wheather there is isinf in noise dataset:
      Noise
0     True
1    False
2    False
3    False
4    False
..     ...
462   True
463  False
464  False
465  False
466  False

[467 rows x 1 columns]
        Noise
0    5.000000
1   -0.334848
2    0.499090
3    0.563460
4    0.791209
..        ...
462  5.000000
463  0.650460
464  0.433990
465 -0.012581
466  0.722683

[467 rows x 1 columns]


In [85]:
# Question 14
clean_noise=noise[~np.isinf(noise)]
print("Removed invalid data",clean_noise)

Removed invalid data         Noise
0    5.000000
1   -0.334848
2    0.499090
3    0.563460
4    0.791209
..        ...
462  5.000000
463  0.650460
464  0.433990
465 -0.012581
466  0.722683

[467 rows x 1 columns]


In [92]:
# Question 15
small_array=np.array([1,])
result4=customer2+small_array
print("Added small array in customer_datset",result4)

Added small array in customer_datset [[nan nan nan nan nan]
 [nan 47. 33. 26. nan]
 [nan 37. 41. 29. nan]
 ...
 [nan 24. 24. 36. nan]
 [nan 32. 32. 31. nan]
 [nan 37. 53. 35. nan]]


In [96]:
# Question 16
copy=customer2.copy()
print("The copied data is \n",copy)
view=customer2.view()
print("The view data is \n",view)

The copied data is 
 [[nan nan nan nan nan]
 [nan 46. 32. 25. nan]
 [nan 36. 40. 28. nan]
 ...
 [nan 23. 23. 35. nan]
 [nan 31. 31. 30. nan]
 [nan 36. 52. 34. nan]]
The view data is 
 [[nan nan nan nan nan]
 [nan 46. 32. 25. nan]
 [nan 36. 40. 28. nan]
 ...
 [nan 23. 23. 35. nan]
 [nan 31. 31. 30. nan]
 [nan 36. 52. 34. nan]]


In [106]:
# Question 17
np.save("customer_data.npy",copy)
load_data=np.load('customer_data.npy')
print("The loaded data is",load_data)
np.savetxt('customer_data.txt',copy,delimiter=',')
loaded=np.genfromtxt('customer_data.txt',delimiter=',')
print("The loaded data is\n",loaded)

The loaded data is [[nan nan nan nan nan]
 [nan 46. 32. 25. nan]
 [nan 36. 40. 28. nan]
 ...
 [nan 23. 23. 35. nan]
 [nan 31. 31. 30. nan]
 [nan 36. 52. 34. nan]]
The loaded data is
 [[nan nan nan nan nan]
 [nan 46. 32. 25. nan]
 [nan 36. 40. 28. nan]
 ...
 [nan 23. 23. 35. nan]
 [nan 31. 31. 30. nan]
 [nan 36. 52. 34. nan]]


In [107]:
# Question 18
image = np.array([[0, 64, 128],[192, 255, 100],[50, 150, 200]])
print("Original Image Matrix:")
print(image)
normalized_image = image / 255
print("\nNormalized Image:")
print(normalized_image)

Original Image Matrix:
[[  0  64 128]
 [192 255 100]
 [ 50 150 200]]

Normalized Image:
[[0.         0.25098039 0.50196078]
 [0.75294118 1.         0.39215686]
 [0.19607843 0.58823529 0.78431373]]


In [ ]:
# Question 19
'''
Question 19 is same as of question 18
'''